<?php
return array (
  'cache_lifetime_channel' => '0',
  'cache_lifetime_index' => '0',
  'cache_lifetime_view' => '0',
  'rewrite_channel' => 'list',
  'rewrite_suffix' => 'html',
  'rewrite_view' => 'view',
  'web_beian' => '',
  'web_caching' => '0',
  'web_close' => '0',
  'web_closecon' => '内有不明生物,关门清除中……',
  'web_debug' => '0',
  'web_default_theme' => 'w',
  'web_description' => '',
  'web_gzip_open' => '0',
  'web_keywords' => '',
  'web_name' => '',
  'web_path_depr' => '-',
  'web_path_suffix' => 'html',
  'web_robot_onnotes' => '1',
  'web_seo_name' => 'A Copy of Online-Bookmarks',
  'web_tongji' => '',
  'web_url' => 'http://w.asunix.tk/',
  'web_url_model' => '1',
  'web_url_route' => 
  array (
    'list' => 'list\\/(\\d+)',
    'list_p' => 'list\\/(\\d+)\\/(\\d+)',
    'show' => 'show\\/(\\d+)',
    'show_p' => 'show\\/(\\d+)\\/(\\d+)',
  ),
  'web_url_route_list' => 'list/{id}',
  'web_url_route_list_p' => 'list/{id}/{page}',
  'web_url_route_on' => '1',
  'web_url_route_show' => 'show/{id}',
  'web_url_route_show_p' => 'show/{id}/{page}',
);
?>